name: setup-aya
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  refs:
    description: branch, tag, or commit of aya-dev
    required: true
    default: nightly-build
  token:
    description: 'github token'
    required: true

outputs:
  version:
    description: the installed aya version

# Define your outputs here.

runs:
  using: "composite"
  steps:
    - name: extract versions
      id: extract-versions
      uses: "aya-prover/aya-dev/.github/workflows/extract-version.yaml@${{ inputs.refs }}"
    - name: checkout
      uses: 'actions/checkout@v4'
      with:
        repository: 'aya-prover/aya-dev'
        ref: ${{ inputs.refs }}
    - name: Setup Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: ${{ steps.extract-versions.outputs.javaVersion }}
    - uses: gradle/gradle-build-action@v3
      with:
        arguments: fatJar --no-daemon --stacktrace --warning-mode all
    - name: Prepare for install
      id: prepare
      shell: bash
      run: |
        cp ./cli-console/build/libs/*-fat.jar ./cli-console/build/libs/cli-fatjar.jar
        echo "aya_root=$PWD" >> $GITHUB_OUTPUT
        echo "version=${{ steps.extract-versions.outputs.projectVersion }}" >> $GITHUB_OUTPUT
    - name: checkout back
      uses: 'actions/checkout@v4'
    - name: Cache Aya
      uses: ./actions/run-me
      with:
        aya-root: ${{ steps.prepare.outputs.aya_root }}
        version: ${{ steps.extract-versions.outputs.projectVersion }}
