name: setup-aya
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  refs:
    description: branch, tag, or commit of aya-dev
    required: true
    default: nightly-build
  token:
    description: 'github token'
    required: true

outputs:
  version:
    description: the installed aya version

# Define your outputs here.

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: 'actions/checkout@v4'
      with:
        repository: 'aya-prover/aya-dev'
        ref: ${{ inputs.refs }}
        path: 'aya-dev'
    - name: Extract versions from Gradle's libs.versions.toml
      id: check
      shell: bash
      working-directory: 'aya-dev'
      run: |
        # We use `head -n1` to select the first line matching the regex, 
        # so be sure to put these versions in the very beginning of the file.
        projectVersion=$(cat ./gradle/libs.versions.toml | grep -Po 'project(\s*)=(\s*)"\K.*?(?=")' | head -n1)
        javaVersion=$(cat ./gradle/libs.versions.toml | grep -Po 'java(\s*)=(\s*)"\K.*?(?=")' | head -n1)

        isSnapshot="$(echo "$projectVersion" | grep -q "SNAPSHOT" && echo true || echo false)"
        echo "Detected Project version: $projectVersion, is snapshot: $isSnapshot, Java version: $javaVersion"

        echo "projectVersion=${projectVersion}" >> $GITHUB_OUTPUT
        echo "isSnapshot=${isSnapshot}" >> $GITHUB_OUTPUT
        echo "javaVersion=${javaVersion}" >> $GITHUB_OUTPUT
    - name: Setup Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: ${{ steps.check.outputs.javaVersion }}
    - name: Build
      uses: gradle/gradle-build-action@v3
      working-directory: 'aya-dev'
      with:
        arguments: fatJar --no-daemon --stacktrace --warning-mode all
    - name: Prepare for install
      id: prepare
      shell: bash
      run: |
        cp ./aya-dev/cli-console/build/libs/*-fat.jar ./cli-fatjar.jar
        echo "version=${{ steps.check.outputs.projectVersion }}" >> $GITHUB_OUTPUT
    - name: Cache Aya
      uses: ./actions/actions/run-me
      with:
        version: ${{ steps.check.outputs.projectVersion }}
