name: setup-aya
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  refs:
    description: branch, tag, or commit of aya-dev
    required: true
    default: nightly-build
  token:
    description: 'github token'
    required: true

# Define your outputs here.

runs:
  using: composite
  steps:
    - name: checkout
      uses: 'actions/checkout@v4'
      with:
        repository: 'aya-prover/aya-dev'
        ref: ${{ inputs.refs }}
    - name: Setup Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: ${{ inputs.java-version }}
    - uses: gradle/gradle-build-action@v3
      with:
        arguments: fatJar --no-daemon --stacktrace --warning-mode all
    - name: Copy fat jar
      shell: bash
      run: |
        cp ./cli-console/build/libs/*-fat.jar ./cli-console/build/libs/cli-fatjar.jar
    - name: Save PWD
      id: save-pwd
      shell: bash
      run: echo "aya_root=$PWD" >> $GITHUB_OUTPUT
    - name: checkout back
      uses: 'actions/checkout@v4'
    - name: Cache Aya
      uses: ./actions/run-me
      with:
        aya-root: ${{ steps.save-pwd.outputs.aya_root }}
